#!/usr/bin/env bash
# task-loop.sh — Agent-agnostic iterative task runner
#
# The Ralph Loop concept (iterate until tests pass), but not locked to any
# single AI coding agent. Works with Claude Code, Cursor, Codex, or any
# tool that accepts a prompt and can run shell commands.
#
# Usage:
#   ./scripts/task-loop.sh                          # interactive mode
#   ./scripts/task-loop.sh --agent claude            # Claude Code
#   ./scripts/task-loop.sh --agent cursor            # Cursor
#   ./scripts/task-loop.sh --agent codex             # Codex
#   ./scripts/task-loop.sh --max-iterations 5        # cap iterations
#
# The loop:
#   1. Read PRD.md for the task definition
#   2. Read progress.md for current state
#   3. Run the agent with the next incomplete task
#   4. Run tests (make test && make lint)
#   5. If tests pass, update progress.md and move to next task
#   6. If tests fail, feed errors back to the agent
#   7. Repeat until all tasks complete or max iterations hit

set -euo pipefail

MAX_ITERATIONS=${MAX_ITERATIONS:-10}
AGENT=${AGENT:-"interactive"}
COMPLETION_MARKER="ALL_TASKS_COMPLETE"
PRD_FILE="PRD.md"
PROGRESS_FILE="progress.md"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log() { echo -e "${CYAN}[task-loop]${NC} $*"; }
ok()  { echo -e "${GREEN}[task-loop]${NC} $*"; }
warn() { echo -e "${YELLOW}[task-loop]${NC} $*"; }
fail() { echo -e "${RED}[task-loop]${NC} $*"; }

# Parse args
while [[ $# -gt 0 ]]; do
    case $1 in
        --agent) AGENT="$2"; shift 2 ;;
        --max-iterations) MAX_ITERATIONS="$2"; shift 2 ;;
        --prd) PRD_FILE="$2"; shift 2 ;;
        *) fail "Unknown arg: $1"; exit 1 ;;
    esac
done

# Check prerequisites
if [[ ! -f "$PRD_FILE" ]]; then
    fail "No $PRD_FILE found. Create one with task definitions first."
    exit 1
fi

# Initialize progress file if it doesn't exist
if [[ ! -f "$PROGRESS_FILE" ]]; then
    cat > "$PROGRESS_FILE" << 'EOF'
# Progress Tracker

## Status: IN_PROGRESS

## Completed Tasks
_none yet_

## Current Task
_starting_

## Failed Attempts
_none_

## Notes
_auto-generated by task-loop.sh_
EOF
    log "Created $PROGRESS_FILE"
fi

run_tests() {
    log "Running tests..."
    if make test 2>&1 && make lint 2>&1; then
        return 0
    else
        return 1
    fi
}

build_prompt() {
    local iteration=$1
    cat << EOF
You are working on the pr-sentinel project. Read these files for context:

## Project Context
$(cat CONTEXT.md)

## Task Definition (PRD)
$(cat "$PRD_FILE")

## Current Progress
$(cat "$PROGRESS_FILE")

## Instructions
1. Find the next incomplete task in the PRD
2. Implement it
3. Run tests: make test && make lint
4. If tests pass, update progress.md marking the task complete
5. If tests fail, fix the errors and try again
6. When ALL tasks are complete, write "$COMPLETION_MARKER" to progress.md

This is iteration $iteration of $MAX_ITERATIONS. Be focused and incremental.
Do ONE task at a time.
EOF
}

# Main loop
iteration=0
while [[ $iteration -lt $MAX_ITERATIONS ]]; do
    iteration=$((iteration + 1))
    log "━━━ Iteration $iteration/$MAX_ITERATIONS ━━━"

    # Check if already complete
    if grep -q "$COMPLETION_MARKER" "$PROGRESS_FILE" 2>/dev/null; then
        ok "All tasks complete! Found $COMPLETION_MARKER in $PROGRESS_FILE"
        exit 0
    fi

    case "$AGENT" in
        claude)
            log "Running Claude Code..."
            claude --permission-mode acceptEdits \
                -p "$(build_prompt $iteration)"
            ;;
        cursor)
            log "Cursor mode — copy the prompt below into Cursor Composer:"
            echo "---"
            build_prompt $iteration
            echo "---"
            read -rp "Press Enter after Cursor finishes, or 'q' to quit: " input
            [[ "$input" == "q" ]] && exit 0
            ;;
        codex)
            log "Running Codex..."
            codex --approval-mode full-auto \
                "$(build_prompt $iteration)"
            ;;
        interactive)
            log "Interactive mode — paste into your preferred AI coding agent:"
            echo ""
            build_prompt $iteration
            echo ""
            read -rp "Press Enter after the agent finishes, or 'q' to quit: " input
            [[ "$input" == "q" ]] && exit 0
            ;;
        *)
            fail "Unknown agent: $AGENT"
            exit 1
            ;;
    esac

    # Verify tests pass
    if run_tests; then
        ok "Tests pass after iteration $iteration"
    else
        warn "Tests failed after iteration $iteration — will retry"
    fi
done

if grep -q "$COMPLETION_MARKER" "$PROGRESS_FILE" 2>/dev/null; then
    ok "All tasks complete in $iteration iterations!"
else
    warn "Hit max iterations ($MAX_ITERATIONS). Check $PROGRESS_FILE for status."
    exit 1
fi
